import Navbar from '../components/navbar'
import Toolbar from '../components/toolbar'
import Footer from '../components/footer'
import './stylecss.css'
import { GlobalContextProvider } from '@/context/store'

export const metadata = {
  title: 'Eezee Assignment',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{backgroundColor: "#EFEFF0", width: "100vw"}}>
        <Navbar />
        <GlobalContextProvider>
          <Toolbar />
          {children}
        </GlobalContextProvider>
        <Footer />
      </body>
    </html>
  )
}
